steps:
  - id: 'yarn:install'
    name: 'node:11-alpine'
    entrypoint: 'yarn'
    args: ['install']

  - id: 'ng:build'
    name: 'node:11-alpine'
    waitFor: ['yarn:install']
    entrypoint: 'ash'
    args:
      - '-c'
      - |
        yarn run ng build --configuration=$BRANCH_NAME
        yarn run webpack --config src/webpack.config.js

  - id: 'docker:build'
    waitFor: ['ng:build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['build',
           '-t', 'eu.gcr.io/$PROJECT_ID/chaud-marais-angular:$SHORT_SHA',
           '.']

  - id: 'docker:push'
    waitFor: ['docker:build']
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'eu.gcr.io/$PROJECT_ID/chaud-marais-angular:$SHORT_SHA']

  - id: 'cloud-run:deploy'
    waitFor: ['docker:push']
    name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud beta run deploy chaud-marais-angular-$BRANCH_NAME \
          --platform=managed \
          --image eu.gcr.io/$PROJECT_ID/chaud-marais-angular:$SHORT_SHA \
          --region europe-west1
